name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: start redpanda
        uses: redpanda-data/github-action@v0.1.3
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
